/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace HushHire {
  export type CandidateStruct = {
    name: string;
    position: string;
    expectedSalary: BigNumberish;
    skills: string;
    isActive: boolean;
  };

  export type CandidateStructOutput = [
    name: string,
    position: string,
    expectedSalary: bigint,
    skills: string,
    isActive: boolean
  ] & {
    name: string;
    position: string;
    expectedSalary: bigint;
    skills: string;
    isActive: boolean;
  };
}

export interface HushHireInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "candidates"
      | "confidentialProtocolId"
      | "getCandidate"
      | "getCandidateCount"
      | "getOfferResult"
      | "getOfferTimestamp"
      | "hasEmployerOffered"
      | "hasOffered"
      | "offerResults"
      | "offerTimestamp"
      | "submitOffer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CandidatesInitialized" | "OfferSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "candidates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOfferResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOfferTimestamp",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEmployerOffered",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOffered",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offerResults",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offerTimestamp",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOffer",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOfferResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOfferTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasEmployerOffered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasOffered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offerResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "offerTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOffer",
    data: BytesLike
  ): Result;
}

export namespace CandidatesInitializedEvent {
  export type InputTuple = [count: BigNumberish];
  export type OutputTuple = [count: bigint];
  export interface OutputObject {
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferSubmittedEvent {
  export type InputTuple = [
    employer: AddressLike,
    candidateId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    employer: string,
    candidateId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    employer: string;
    candidateId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HushHire extends BaseContract {
  connect(runner?: ContractRunner | null): HushHire;
  waitForDeployment(): Promise<this>;

  interface: HushHireInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  candidates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        name: string;
        position: string;
        expectedSalary: bigint;
        skills: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getCandidate: TypedContractMethod<
    [candidateId: BigNumberish],
    [HushHire.CandidateStructOutput],
    "view"
  >;

  getCandidateCount: TypedContractMethod<[], [bigint], "view">;

  getOfferResult: TypedContractMethod<
    [candidateId: BigNumberish],
    [string],
    "view"
  >;

  getOfferTimestamp: TypedContractMethod<
    [employer: AddressLike, candidateId: BigNumberish],
    [bigint],
    "view"
  >;

  hasEmployerOffered: TypedContractMethod<
    [employer: AddressLike, candidateId: BigNumberish],
    [boolean],
    "view"
  >;

  hasOffered: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  offerResults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  offerTimestamp: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  submitOffer: TypedContractMethod<
    [candidateId: BigNumberish, encryptedOffer: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "candidates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        name: string;
        position: string;
        expectedSalary: bigint;
        skills: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCandidate"
  ): TypedContractMethod<
    [candidateId: BigNumberish],
    [HushHire.CandidateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCandidateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOfferResult"
  ): TypedContractMethod<[candidateId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getOfferTimestamp"
  ): TypedContractMethod<
    [employer: AddressLike, candidateId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEmployerOffered"
  ): TypedContractMethod<
    [employer: AddressLike, candidateId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasOffered"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "offerResults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "offerTimestamp"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitOffer"
  ): TypedContractMethod<
    [candidateId: BigNumberish, encryptedOffer: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CandidatesInitialized"
  ): TypedContractEvent<
    CandidatesInitializedEvent.InputTuple,
    CandidatesInitializedEvent.OutputTuple,
    CandidatesInitializedEvent.OutputObject
  >;
  getEvent(
    key: "OfferSubmitted"
  ): TypedContractEvent<
    OfferSubmittedEvent.InputTuple,
    OfferSubmittedEvent.OutputTuple,
    OfferSubmittedEvent.OutputObject
  >;

  filters: {
    "CandidatesInitialized(uint256)": TypedContractEvent<
      CandidatesInitializedEvent.InputTuple,
      CandidatesInitializedEvent.OutputTuple,
      CandidatesInitializedEvent.OutputObject
    >;
    CandidatesInitialized: TypedContractEvent<
      CandidatesInitializedEvent.InputTuple,
      CandidatesInitializedEvent.OutputTuple,
      CandidatesInitializedEvent.OutputObject
    >;

    "OfferSubmitted(address,uint256,uint256)": TypedContractEvent<
      OfferSubmittedEvent.InputTuple,
      OfferSubmittedEvent.OutputTuple,
      OfferSubmittedEvent.OutputObject
    >;
    OfferSubmitted: TypedContractEvent<
      OfferSubmittedEvent.InputTuple,
      OfferSubmittedEvent.OutputTuple,
      OfferSubmittedEvent.OutputObject
    >;
  };
}
